server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./data/testdb;MODE=MySQL # ./ Project root embedded mode
#      jdbc-url: jdbc:h2:tcp://localhost:9092/./data/testdb server-mode
#      jdbc-url: jdbc:h2:mem:testdb # in-memory-mode
      username: sa
      password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true


---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb